import {
  PracticeIndexItem,
  PracticeIndexCategory,
  V2PeriodData,
  V2PostGameData,
} from '@/types/charting';
import { PillarSlug } from '@/types/onboarding';

type PeriodKey = 'period1' | 'period2' | 'period3' | 'overtime';

const PERIOD_LABELS: Record<PeriodKey, string> = {
  period1: 'Period 1',
  period2: 'Period 2',
  period3: 'Period 3',
  overtime: 'Overtime',
};

function makeId(sessionId: string, field: string): string {
  return `pi_auto_${sessionId.slice(-6)}_${field}_${Date.now().toString(36)}`;
}

function item(
  sessionId: string,
  label: string,
  category: PracticeIndexCategory,
  pillarSlug: PillarSlug,
  sourceField: string,
  description?: string,
): PracticeIndexItem {
  const priority = category === 'immediate_development' ? 1 : category === 'refinement' ? 2 : 3;
  return {
    id: makeId(sessionId, sourceField),
    label,
    description,
    category,
    pillarSlug,
    autoGenerated: true,
    sourceGameSessionId: sessionId,
    sourceField,
    priority,
  };
}

/**
 * Generates a PracticeIndexItem[] from a completed game charting entry.
 * Called at post-game save time and stored on the charting entry as v2PracticeIndex.
 */
export function generatePracticeIndex(
  v2Periods: Record<string, V2PeriodData>,
  v2PostGame: V2PostGameData,
  sessionId: string,
): PracticeIndexItem[] {
  const items: PracticeIndexItem[] = [];
  const activePeriods = Object.entries(v2Periods).filter(
    ([, p]) => p !== null && p !== undefined,
  ) as [string, V2PeriodData][];

  // ── Mind Control per period (Mindset Pillar) ─────────────────────────────
  let hasMindImmediate = false;
  let hasMindRefinement = false;

  for (const [key, period] of activePeriods) {
    const label = PERIOD_LABELS[key as PeriodKey] ?? key;
    if ((period.mindControlRating ?? 0) <= 2) {
      items.push(item(
        sessionId,
        `Mind Control Breakdown — ${label}`,
        'immediate_development',
        'mindset',
        `mindControlRating_${key}`,
        `Rated ${period.mindControlRating}/5. Focus broke down this period.${period.mindControlVoiceNote ? ` Note: "${period.mindControlVoiceNote}"` : ' Review what pulled your attention away.'}`,
      ));
      hasMindImmediate = true;
    } else if (period.mindControlRating === 3) {
      items.push(item(
        sessionId,
        `Mind Control Consistency — ${label}`,
        'refinement',
        'mindset',
        `mindControlRating_${key}`,
        `Rated 3/5. Building but not yet consistent. Work on sustaining focus across the full period.`,
      ));
      hasMindRefinement = true;
    }
  }

  // No low-mind-control periods — add maintenance
  if (!hasMindImmediate && !hasMindRefinement && activePeriods.length > 0) {
    items.push(item(
      sessionId,
      'Maintain Mind Command',
      'maintenance',
      'mindset',
      'mindControlRating_overall',
      'Strong mental command across all periods. Sustain the standard.',
    ));
  }

  // ── Game Retention (Mindset Pillar) ─────────────────────────────────────
  const retention = v2PostGame.gameRetentionRating ?? 0;
  if (retention <= 2) {
    items.push(item(
      sessionId,
      'Game Retention — Develop Recall',
      'immediate_development',
      'mindset',
      'gameRetentionRating',
      `Rated ${retention}/5. Game memory is unclear. Video review and structured post-game recall routines recommended.`,
    ));
  } else if (retention === 3) {
    items.push(item(
      sessionId,
      'Game Retention — Build Consistency',
      'refinement',
      'mindset',
      'gameRetentionRating',
      `Rated ${retention}/5. Some periods are clear. Build the habit of active recall immediately after each period.`,
    ));
  }

  // ── Bad Goals (Positioning Pillar) ───────────────────────────────────────
  const badGoals = v2PostGame.badGoalCount ?? 0;
  const goodGoals = v2PostGame.goodGoalCount ?? 0;
  const totalGoals = badGoals + goodGoals;

  if (badGoals >= 3) {
    items.push(item(
      sessionId,
      `Goal Breakdown Review — ${badGoals} Bad Goal${badGoals > 1 ? 's' : ''}`,
      'immediate_development',
      'positioning',
      'badGoalCount',
      `${badGoals} goals within your control this game. Work backward from each: position → read → decision → execution.`,
    ));
  } else if (badGoals === 1 || badGoals === 2) {
    items.push(item(
      sessionId,
      `Decision Review — ${badGoals} Bad Goal${badGoals > 1 ? 's' : ''}`,
      'refinement',
      'positioning',
      'badGoalCount',
      `${badGoals} correctable goal${badGoals > 1 ? 's' : ''}. Review the position/read/decision that broke down.`,
    ));
  }

  // All goals good (and there were goals) → form maintenance
  if (totalGoals > 0 && badGoals === 0) {
    items.push(item(
      sessionId,
      'Perfect Decision Rate — Maintain Standards',
      'maintenance',
      'form',
      'goodDecisionRate',
      `100% good decision rate (${goodGoals} goal${goodGoals > 1 ? 's' : ''}, all classified good). Hold this standard.`,
    ));
  }

  // ── High Challenge × Low Mind Control (Mindset Pillar) ──────────────────
  const mindAvg = v2PostGame.mindControlAverage ?? 0;
  const factorRating = v2PostGame.overallGameFactorRating ?? 0;

  if (factorRating >= 4 && mindAvg > 0 && mindAvg <= 2.5 && !hasMindImmediate) {
    items.push(item(
      sessionId,
      'High Pressure Mental Game',
      'immediate_development',
      'mindset',
      'overallGameFactorRating_x_mindControlAverage',
      `${factorRating}/5 challenge game with ${mindAvg.toFixed(1)}/5 mind control avg. Mental game broke down under maximum pressure — this is the practice priority.`,
    ));
  } else if (factorRating >= 4 && mindAvg >= 4) {
    items.push(item(
      sessionId,
      'Elite Pressure Performance',
      'maintenance',
      'mindset',
      'overallGameFactorRating_x_mindControlAverage',
      `Maintained ${mindAvg.toFixed(1)}/5 mind control in a ${factorRating}/5 challenge game. Elite mental standard — keep it.`,
    ));
  }

  // Sort: immediate first, then refinement, then maintenance
  return items.sort((a, b) => a.priority - b.priority);
}
