import { Course } from '@/types/course';

export const sampleCourses: Omit<Course, 'id' | 'createdAt' | 'updatedAt' | 'createdBy'>[] = [
  // Basketball Courses
  {
    title: 'Basketball Fundamentals',
    description: 'Master the basic skills of basketball including dribbling, shooting, and passing',
    sportId: 'basketball', // This should match the actual sport ID
    difficulty: 'beginner',
    duration: 8, // 8 hours
    category: 'Fundamentals',
    tags: ['dribbling', 'shooting', 'passing', 'fundamentals'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Advanced Shooting Techniques',
    description: 'Perfect your shooting form and accuracy with advanced techniques and drills',
    sportId: 'basketball',
    difficulty: 'intermediate',
    duration: 6,
    category: 'Shooting',
    tags: ['shooting', 'accuracy', 'form', 'three-pointers'],
    isActive: true,
    isFeatured: false,
  },
  {
    title: 'Defensive Strategies',
    description: 'Learn man-to-man and zone defense strategies',
    sportId: 'basketball',
    difficulty: 'intermediate',
    duration: 5,
    category: 'Defense',
    tags: ['defense', 'strategy', 'positioning'],
    isActive: true,
    isFeatured: false,
  },
  {
    title: 'Basketball IQ & Game Strategy',
    description: 'Develop court vision and strategic thinking for advanced gameplay',
    sportId: 'basketball',
    difficulty: 'advanced',
    duration: 10,
    category: 'Strategy',
    tags: ['strategy', 'court-vision', 'game-iq', 'advanced'],
    isActive: true,
    isFeatured: true,
  },

  // Soccer Courses
  {
    title: 'Soccer Fundamentals',
    description: 'Learn basic ball control, passing, and movement on the field',
    sportId: 'soccer',
    difficulty: 'beginner',
    duration: 10,
    category: 'Fundamentals',
    tags: ['ball-control', 'passing', 'movement', 'basics'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Ball Control Mastery',
    description: 'Advanced ball control techniques and close control skills',
    sportId: 'soccer',
    difficulty: 'intermediate',
    duration: 7,
    category: 'Technical Skills',
    tags: ['ball-control', 'dribbling', 'first-touch', 'technique'],
    isActive: true,
    isFeatured: false,
  },
  {
    title: 'Goalkeeping Essentials',
    description: 'Complete goalkeeper training from basic saves to advanced positioning',
    sportId: 'soccer',
    difficulty: 'intermediate',
    duration: 8,
    category: 'Goalkeeping',
    tags: ['goalkeeping', 'saves', 'positioning', 'distribution'],
    isActive: true,
    isFeatured: false,
  },
  {
    title: 'Tactical Awareness',
    description: 'Understanding formations, positioning, and tactical play',
    sportId: 'soccer',
    difficulty: 'advanced',
    duration: 12,
    category: 'Tactics',
    tags: ['tactics', 'formations', 'positioning', 'strategy'],
    isActive: true,
    isFeatured: true,
  },

  // Tennis Courses
  {
    title: 'Tennis Fundamentals',
    description: 'Master the basic strokes: forehand, backhand, serve, and volley',
    sportId: 'tennis',
    difficulty: 'beginner',
    duration: 6,
    category: 'Fundamentals',
    tags: ['strokes', 'forehand', 'backhand', 'serve', 'basics'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Tennis Serve Mastery',
    description: 'Perfect your serve technique and add power and precision',
    sportId: 'tennis',
    difficulty: 'intermediate',
    duration: 4,
    category: 'Serving',
    tags: ['serve', 'power', 'accuracy', 'technique'],
    isActive: true,
    isFeatured: false,
  },
  {
    title: 'Professional Tennis Techniques',
    description: 'Advanced techniques used by professional players',
    sportId: 'tennis',
    difficulty: 'advanced',
    duration: 15,
    category: 'Advanced',
    tags: ['professional', 'advanced', 'tournament', 'competition'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Mental Game in Tennis',
    description: 'Develop mental toughness and concentration for competitive play',
    sportId: 'tennis',
    difficulty: 'intermediate',
    duration: 5,
    category: 'Mental Game',
    tags: ['mental', 'concentration', 'competition', 'psychology'],
    isActive: true,
    isFeatured: false,
  },

  // Swimming Courses
  {
    title: 'Swimming Fundamentals',
    description: 'Learn basic swimming strokes and water safety',
    sportId: 'swimming',
    difficulty: 'beginner',
    duration: 8,
    category: 'Fundamentals',
    tags: ['strokes', 'safety', 'breathing', 'basics'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Competitive Swimming',
    description: 'Training for competitive swimming and race preparation',
    sportId: 'swimming',
    difficulty: 'advanced',
    duration: 12,
    category: 'Competition',
    tags: ['competition', 'racing', 'technique', 'endurance'],
    isActive: true,
    isFeatured: false,
  },

  // Baseball Courses
  {
    title: 'Baseball Fundamentals',
    description: 'Learn hitting, fielding, and base running basics',
    sportId: 'baseball',
    difficulty: 'beginner',
    duration: 10,
    category: 'Fundamentals',
    tags: ['hitting', 'fielding', 'base-running', 'basics'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Pitching Mechanics',
    description: 'Master proper pitching form and different pitch types',
    sportId: 'baseball',
    difficulty: 'intermediate',
    duration: 8,
    category: 'Pitching',
    tags: ['pitching', 'mechanics', 'fastball', 'curveball'],
    isActive: true,
    isFeatured: false,
  },

  // Golf Courses
  {
    title: 'Golf Fundamentals',
    description: 'Learn proper golf swing, putting, and course management',
    sportId: 'golf',
    difficulty: 'beginner',
    duration: 12,
    category: 'Fundamentals',
    tags: ['swing', 'putting', 'course-management', 'basics'],
    isActive: true,
    isFeatured: true,
  },
  {
    title: 'Advanced Golf Techniques',
    description: 'Shot shaping, advanced course strategy, and mental game',
    sportId: 'golf',
    difficulty: 'advanced',
    duration: 15,
    category: 'Advanced',
    tags: ['shot-shaping', 'strategy', 'mental-game', 'advanced'],
    isActive: true,
    isFeatured: false,
  },
];